### ISSUE TITLE
"Menu page title" does not support non-ASCII characters

### ISSUE THREAD

**Issue by ricardopadilha** [poolghost/adminoptionspages-issues#4]
I just tried creating a page using a unicode character ("á" or `&acute;`), and when I click save I get an error message asking "Are you trying to break something?".

Reproducing this is very simple: create a new page, enter a menu page title with a latin character (e.g., "Página de teste") and it will fail to save. Using the exact same string, but without the accent works (i.e., "Pagina de teste").

![image](https://user-images.githubusercontent.com/1210756/131721002-0ee197f3-548f-4913-9c27-d14ae68d57fc.png)

Note: this does not affect the "Page title", only the "Menu page title".

**Comment by poolghost** [comment]
Fixed. See -> https://nl.wordpress.org/plugins/admin-options-pages/#developers

**Comment by ricardopadilha** [comment]
Thanks a lot for the fix. I suspect that this also has fixed #3. I'm currently testing it on a few sites, I'll update that ticket with confirmation.

**Comment by thuanqt** [comment]
"Menu page title" does not support Unicode characters "Cài đặt"
